parameters:
    cron_event.streamhandler.class:        Monolog\Handler\StreamHandler
    cron_event.streamhandler.level:        %cron_event.logger.class%::DEBUG

    cron_event.firephphandler.class:       Monolog\Handler\FirePHPHandler

    cron_event.logger.class:               Monolog\Logger
    cron_event.logger.name:                cron
    cron_event.logger.logs_file_path:      %kernel.logs_dir%/%cron_event.logger.name%.log

services:
    cron_event.streamhandler:
        class: %cron_event.streamhandler.class%
        arguments:
          - %cron_event.logger.logs_file_path%
          - %cron_event.streamhandler.level%

    cron_event.firephphandler:
        class: %cron_event.firephphandler.class%

    cron_event.logger.parent:
        abstract: true
        class: %cron_event.logger.class%
        calls:
          - [pushHandler, [@cron_event.streamhandler, @cron_event.firephphandler]]

    cron_event.logger:
        parent: cron_event.logger.parent
        arguments:
          - %cron_event.logger.name%