imports:
    - { resource: logs.yml }

parameters:
       cron_event.general.event.class: Litvinab\Bundle\CronEventBundle\Events\LitvinabEvent
       cron_event.general.listener.class: Litvinab\Bundle\CronEventBundle\EventListener\CronListener

services:
      cron-event.repository.schedule:
         class: Doctrine\ODM\DocumentRepository
         factory_service: doctrine_mongodb.odm.document_manager
         factory_method: getRepository
         arguments:
           - Litvinab\Bundle\CronEventBundle\Document\Schedule

      cron-event.model.schedule:
         class: Litvinab\Bundle\CronEventBundle\Model\ScheduleModel
         arguments:
           - "@cron-event.repository.schedule"
           - "@doctrine.odm.mongodb.document_manager"

      cron_event.manager:
         class: Litvinab\Bundle\CronEventBundle\Service\CronManager
         calls:
            - [setDispatcher, [@event_dispatcher]]
            - [setScheduleModel, [@cron-event.model.schedule]]

      kernel.listener.cron_manager:
         class: Litvinab\Bundle\CronEventBundle\EventListener\CronListener
         arguments:
             - "@cron_event.manager"
         tags:
             - { name: kernel.event_listener, event: cron.run, method: onCron }